project:
  type: website

website:
  title: "Jen Richmond"
  google-analytics: "G-Y7WV5KV7Z0"
  navbar:
    left:
      - href: index.qmd
        text: home
      - about.qmd
      - posts.qmd
      - text: "data viz"
        menu: 
          - text: "30DayChartChallenge"
            href: charts_30day.qmd
          - text: "TidyTuesday"
            href: charts_tidytuesday.qmd
          - text: "30DayMapChallenge"
            href: maps_30day.qmd
      - projects.qmd
      - resume.qmd
      
    right:
      - icon: github
        href: https://github.com/jenrichmond
      - icon: linkedin
        href: https://www.linkedin.com/in/jenrichmondphd/
      - text: "{{< iconify fa6-brands bluesky size=1.1em title='Bluesky' >}}"
        href: https://bsky.app/profile/jenrichmondphd.bsky.social
      - icon: envelope
        text: Email
        href: mailto:jennyrichmond@gmail.com


  search:
    location: navbar
    type: overlay
  page-footer:
      left: "&#169; 2024 Jen Richmond"
      center: |
        <a class="link-dark me-1" href="https://github.com/jenrichmond" title="github" target="_blank" rel="noopener">{{< iconify fa6-brands github >}}</a>
        <a class="link-dark me-1" href="https://www.linkedin.com/in/jenrichmondphd/" title="LinkedIn" target="_blank" rel="noopener">{{< iconify fa6-brands linkedin >}}</a>
        <a class="link-dark me-1" href="https://bsky.app/profile/jenrichmondphd.bsky.social" title="Bluesky" target="_blank" rel="noopener">{{< iconify fa6-brands bluesky >}}</a>
      right: |
        <a class="link-dark me-1" href="https://github.com/jenrichmond/jenrichmond.github.io">{{< iconify fa6-brands github >}} Source</a>


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
execute:
  freeze: true  # or 'auto'

  

